rawdata=$"/mnt/research/ged/tamer/dogseq/data"
dogSeq=$"/mnt/ls15/scratch/users/mansourt/Tamer/dogSeq"
script_path=$"/mnt/ls15/scratch/users/mansourt/Tamer/dogSeq/scripts"
workingdata=$"/mnt/ls15/scratch/users/mansourt/Tamer/dogSeq/data"
genome_dir=$"/mnt/ls15/scratch/users/mansourt/Tamer/dogSeq/refGenome"
varResults=$"/mnt/ls15/scratch/users/mansourt/Tamer/dogSeq/varResults"
varResults_snps=$"/mnt/ls15/scratch/users/mansourt/Tamer/dogSeq/varResults_snps"
varResults_indels=$"/mnt/ls15/scratch/users/mansourt/Tamer/dogSeq/varResults_indels"
Bwa_ref="$genome_dir/BwaIndex/genome.fa"
gatk_ref="$genome_dir/gatkIndex/genome.fa"
gatk_ref_index="$genome_dir/gatkIndex/genome.fa.fai"
knownSNPs1="$genome_dir/knowVar/canis_familiaris_SNPs.vcf"
knownIndels="$genome_dir/knowVar/canis_familiaris_indels.vcf"
knownSNPs2="$genome_dir/knowVar/Broad.SNPs.vcf"
knownSNPs="$genome_dir/knowVar/combine_union.vcf"

snps="GenotypeGVCFs_output_max50.pass_snps"
indels="GenotypeGVCFs_output_max50.pass_indels"
breedSp="$varResults/breedSp"


